apiVersion: v1
kind: Service
metadata:
  name: completion-server-svc
  labels:
    run: completion-server-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: completion
